# @package _global_

# Data source specific configurations
# Extracted from hardcoded values in bioinformatics modules

data_sources:
  go:
    enabled: true
    evidence_codes: ${bioinformatics.evidence_codes.high_quality}
    year_min: ${bioinformatics.temporal.ncRNA_min_year}
    quality_threshold: ${bioinformatics.quality.default_threshold}
    include_obsolete: false
    namespace_filter: ["biological_process", "molecular_function", "cellular_component"]

  pubmed:
    enabled: true
    max_results: ${bioinformatics.pubmed.default_max_results}
    include_full_text: ${bioinformatics.pubmed.include_full_text}
    year_min: ${bioinformatics.pubmed.default_year_min}
    include_abstract: true
    include_mesh_terms: true
    include_keywords: true
    open_access_only: false

  geo:
    enabled: true
    include_expression: ${bioinformatics.geo.include_expression}
    max_series: ${bioinformatics.geo.default_max_series}
    max_samples_per_series: ${bioinformatics.geo.max_samples_per_series}
    include_platform_info: true
    include_sample_characteristics: true

  drugbank:
    enabled: true
    include_targets: ${bioinformatics.drugbank.include_targets}
    include_mechanisms: ${bioinformatics.drugbank.include_mechanisms}
    include_indications: ${bioinformatics.drugbank.include_indications}
    include_clinical_phase: true
    include_action_type: true

  pdb:
    enabled: true
    include_interactions: ${bioinformatics.pdb.include_interactions}
    resolution_max: ${bioinformatics.pdb.resolution_max}
    include_sequences: ${bioinformatics.pdb.include_sequences}
    include_secondary_structure: ${bioinformatics.pdb.include_secondary_structure}
    include_binding_sites: true
    include_publication_info: true

  intact:
    enabled: true
    confidence_min: ${bioinformatics.intact.default_confidence_min}
    include_detection_method: true
    include_species: true
    include_publication_refs: true

  uniprot:
    enabled: true
    include_sequences: true
    include_features: true
    include_cross_references: true

  cmap:
    enabled: true
    include_connectivity_scores: true
    include_p_values: true
    include_cell_lines: true
    include_concentrations: true
    include_time_points: true
